KUSYS-Demo.WebUI/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KUSYS_Demo.Data.Abstract;
using KUSYS_Demo.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace KUSYS_Demo.WebUI.Controllers
{
    /// <summary>
    /// Only the admin role can
    /// </summary>
    [Authorize(Policy = "AdminRolePolicy")]
    public class CourseController : Controller
    {
        IUnitOfWork unitOfWork;
        public CourseController(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        /// <summary>
        /// Course list method
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var courseList = unitOfWork.Courses.GetAll()
                .Select(s => new CourseListViewModel
                {
                    CourseId = s.CourseId,
                    CourseName = s.CourseName
                });

            return View(courseList);
        }

        /// <summary>
        /// CourseAdd Get Method
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult AddCourse()
        {
            return View();
        }

        /// <summary>
        /// CourseAdd Post Method
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult AddCourse(CourseListViewModel model)
        {
            if (ModelState.IsValid)
            {
                Data.Utilities.Models.CourseViewModel courseViewModel = new Data.Utilities.Models.CourseViewModel();
                courseViewModel.CourseName = model.CourseName;
                courseViewModel.CourseId = model.CourseId;
                unitOfWork.Courses.AddCourse(courseViewModel);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        /// <summary>
        /// CourseUpdate Get Method
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult UpdateCourse(string id)
        {
            var course = unitOfWork.Courses.GetAll().FirstOrDefault(x => x.CourseId == id);
            CourseListViewModel courseListViewModel = new CourseListViewModel();
            courseListViewModel.CourseId = course.CourseId;
            courseListViewModel.CourseName = course.CourseName;
            return View(courseListViewModel);
        }

        /// <summary>
        /// CourseUpdate Post Method
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult UpdateCourse(CourseListViewModel model)
        {
            Data.Utilities.Models.CourseViewModel courseViewModel = new Data.Utilities.Models.CourseViewModel();
            courseViewModel.CourseId = model.CourseId;
            courseViewModel.CourseName = model.CourseName;
            unitOfWork.Courses.UpdateCourse(courseViewModel);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// CourseDelete Method
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult DeleteCourse(string id)
        {
            unitOfWork.Courses.DeleteCourse(id);

            return RedirectToAction("Index");
        }
    }
}

KUSYS-Demo.WebUI/Controllers/MatchingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KUSYS_Demo.Data.Abstract;
using KUSYS_Demo.Identity;
using KUSYS_Demo.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace KUSYS_Demo.WebUI.Controllers
{
    /// <summary>
    /// Only the admin role can
    /// </summary>
    [Authorize(Policy = "AdminRolePolicy")]
    public class MatchingController : Controller
    {
        IUnitOfWork unitOfWork;
        private UserManager<ApplicationUser> userManager;
        private RoleManager<ApplicationRole> roleManager;
        public MatchingController(IUnitOfWork _unitOfWork, UserManager<ApplicationUser> _userManager, RoleManager<ApplicationRole> _roleManager)
        {
            unitOfWork = _unitOfWork;
            userManager = _userManager;
            roleManager = _roleManager;
        }

        /// <summary>
        /// List of student and course matchings
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            List<StudentListViewModel> studentList = new List<StudentListViewModel>();
            studentList = unitOfWork.Students.GetAll()
                .Select(s => new StudentListViewModel
                {
                    StudentId = s.StudentId,
                    FirstName = s.FirstName,
                    LastName = s.LastName,
                    BirthDate = s.BirthDate,
                    PhoneNumber = s.PhoneNumber,
                    Address = s.Address,
                    EMail = s.EMail,
                    UserName = s.UserName
                }).ToList();
            foreach (var item in studentList)
            {
                var matchings = unitOfWork.Matchings.GetAll().Where(x => x.StudentId == item.StudentId).ToList();
                item.Courses = new List<CourseListViewModel>();
                foreach (var matching in matchings)
                {
                    var course = unitOfWork.Courses.GetAll().FirstOrDefault(f => f.CourseId == matching.CourseId);
                    CourseListViewModel model = new CourseListViewModel();
                    model.CourseId = course.CourseId;
                    model.CourseName = course.CourseName;
                    item.Courses.Add(model);
                }
                item.Course = String.Join(",", item.Courses.Select(s => s.CourseName));
            }

            return View(studentList);
        }
    }
}

KUSYS-Demo.WebUI/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KUSYS_Demo.Data.Abstract;
using KUSYS_Demo.Data.Utilities.Models;
using KUSYS_Demo.Entity;
using KUSYS_Demo.Identity;
using KUSYS_Demo.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace KUSYS_Demo.WebUI.Controllers
{
    public class StudentController : Controller
    {
        IUnitOfWork unitOfWork;
        private UserManager<ApplicationUser> userManager;
        private RoleManager<ApplicationRole> roleManager;

        public StudentController(IUnitOfWork _unitOfWork, UserManager<ApplicationUser> _userManager, RoleManager<ApplicationRole> _roleManager)
        {
            unitOfWork = _unitOfWork;
            userManager = _userManager;
            roleManager = _roleManager;
        }
        /// <summary>
        /// Student list and show detail
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            List<StudentListViewModel> studentList = new List<StudentListViewModel>();
            studentList = unitOfWork.Students.GetAll()
                .Select(s => new StudentListViewModel
                {
                    StudentId = s.StudentId,
                    FirstName = s.FirstName,
                    LastName = s.LastName,
                    BirthDate = s.BirthDate,
                    PhoneNumber = s.PhoneNumber,
                    Address = s.Address,
                    EMail = s.EMail,
                    UserName = s.UserName
                }).ToList();
            return View(studentList);
        }

        /// <summary>
        /// Only the admin role can add students. (StudentAdd Get method)
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Policy = "AdminRolePolicy")]
        public IActionResult AddStudent()
        {
            StudentListViewModel model = new StudentListViewModel();
            var courses = unitOfWork.Courses.GetAll().Select(s => new CourseListViewModel
            {
                CourseId = s.CourseId,
                CourseName = s.CourseName
            }).ToList();
            model.Courses = new List<CourseListViewModel>();
            model.Courses.AddRange(courses);
            return View(model);
        }
        /// <summary>
        /// Only the admin role can add students. (StudentAdd Post Method)
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Policy = "AdminRolePolicy")]
        public IActionResult AddStudent(StudentListViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser
                {
                    UserName = model.UserName,
                    Email = model.EMail,
                    Name = model.FirstName + " " + model.LastName,
                    IsActive = true,
                    PhoneNumber = model.PhoneNumber,
                    IdentityId = Guid.NewGuid()
                };

                var result = userManager.CreateAsync(user, model.Password).GetAwaiter().GetResult();

                if (result.Succeeded)
                {
                    var roles = userManager.GetRolesAsync(user).GetAwaiter().GetResult();
                    List<string> role = new List<string>();
                    role.Add("User");

                    result = userManager.AddToRolesAsync(user, role).GetAwaiter().GetResult();

                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError("", "Seçilen roller kullanıcıya eklenemiyor.");
                        return View(model);
                    }

                    Data.Utilities.Models.StudentViewModel studentViewModel = new Data.Utilities.Models.StudentViewModel();
                    studentViewModel.FirstName = model.FirstName;
                    studentViewModel.LastName = model.LastName;
                    studentViewModel.BirthDate = model.BirthDate;
                    studentViewModel.PhoneNumber = model.PhoneNumber;
                    studentViewModel.Address = model.Address;
                    studentViewModel.EMail = model.EMail;
                    studentViewModel.UserName = model.UserName;
                    studentViewModel.Password = model.Password;
                    studentViewModel.IdentityId = user.IdentityId;

                    studentViewModel.Courses = new List<Data.Utilities.Models.CourseViewModel>();
                    foreach (var course in model.Courses)
                    {
                        Data.Utilities.Models.CourseViewModel courseViewModel = new Data.Utilities.Models.CourseViewModel();
                        if (course.IsSelected)
                        {
                            courseViewModel.CourseId = course.CourseId;
                            courseViewModel.CourseName = course.CourseName;
                            studentViewModel.Courses.Add(courseViewModel);
                        }
                    }


                    unitOfWork.Students.AddStudent(studentViewModel);
                }
                
                return RedirectToAction("Index");
            }
            else
            {
                var courses = unitOfWork.Courses.GetAll().Select(s => new CourseListViewModel
                {
                    CourseId = s.CourseId,
                    CourseName = s.CourseName
                }).ToList();
                model.Courses = new List<CourseListViewModel>();
                model.Courses.AddRange(courses);
                return View(model);
            }
        }

        /// <summary>
        /// Admin can update all students. But the user can only update his own information. (StudentUpdate Get Method)
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Policy = "AdminUserPolicy")]
        public IActionResult UpdateStudent(int id)
        {
            Guid identityId = new Guid(HttpContext.User.Claims.FirstOrDefault(x => x.Type == "IdentityId").Value);
            var student = unitOfWork.Students.Get(id);
            if (student.IdentityId == identityId)
            {
                StudentListViewModel studentListViewModel = new StudentListViewModel();
                studentListViewModel.StudentId = student.StudentId;
                studentListViewModel.FirstName = student.FirstName;
                studentListViewModel.LastName = student.LastName;
                studentListViewModel.BirthDate = student.BirthDate;
                studentListViewModel.PhoneNumber = student.PhoneNumber;
                studentListViewModel.Address = student.Address;
                studentListViewModel.EMail = student.EMail;

                var mathings = unitOfWork.Matchings.GetAll().Where(x => x.StudentId == student.StudentId).ToList();
                var courses = mathings.Select(s => s.CourseId).ToList();
                studentListViewModel.Courses = new List<CourseListViewModel>();
                if (mathings != null && mathings.Count() > 0)
                {
                    var courseList = unitOfWork.Courses.GetAll().Where(x => !courses.Contains(x.CourseId)).ToList();
                    if (courseList != null && courseList.Count() > 0)
                    {
                        foreach (var item in courseList)
                        {
                            CourseListViewModel courseViewModel = new CourseListViewModel();
                            courseViewModel.CourseId = item.CourseId;
                            courseViewModel.CourseName = item.CourseName;
                            studentListViewModel.Courses.Add(courseViewModel);
                        }
                    }
                }
                else
                {
                    var courseslist = unitOfWork.Courses.GetAll().Select(s => new CourseListViewModel
                    {
                        CourseId = s.CourseId,
                        CourseName = s.CourseName
                    }).ToList();

                    studentListViewModel.Courses.AddRange(courseslist);
                }

                return View(studentListViewModel);
            }
            else
            {
                return RedirectToAction("AccessDenied", "Account");
            }
        }

        /// <summary>
        /// Admin can update all students. But the user can only update his own information. (StudentUpdate Post Method)
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Policy = "AdminUserPolicy")]
        public IActionResult UpdateStudent(StudentListViewModel model)
        {
            Data.Utilities.Models.StudentViewModel studentViewModel = new Data.Utilities.Models.StudentViewModel();
            studentViewModel.StudentId = model.StudentId;
            studentViewModel.FirstName = model.FirstName;
            studentViewModel.LastName = model.LastName;
            studentViewModel.BirthDate = model.BirthDate;
            studentViewModel.PhoneNumber = model.PhoneNumber;
            studentViewModel.Address = model.Address;
            studentViewModel.EMail = model.EMail;

            studentViewModel.Courses = new List<Data.Utilities.Models.CourseViewModel>();
            foreach (var course in model.Courses)
            {
                Data.Utilities.Models.CourseViewModel courseViewModel = new Data.Utilities.Models.CourseViewModel();
                if (course.IsSelected)
                {
                    courseViewModel.CourseId = course.CourseId;

KUSYS-Demo.WebUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@using System.Security.Claims
@inject IAuthorizationService authorizationService
<!DOCTYPE html>

<!-- =========================================================
* Sneat - Bootstrap 5 HTML Admin Template - Pro | v1.0.0
==============================================================

* Product Page: https://themeselection.com/products/sneat-bootstrap-html-admin-template/
* Created by: ThemeSelection
* License: You must have a valid license purchased in order to legally use the theme for your project.
* Copyright ThemeSelection (https://themeselection.com)

=========================================================
 -->
<!-- beautify ignore:start -->
<html lang="en"
      class="light-style layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="~/sneat/assets/"
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Container - Layouts | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/sneat/assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/sneat/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/sneat/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/sneat/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/sneat/assets/css/demo.css" />
    <link href="~/DataTables/datatables.min.css" rel="stylesheet" />
    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="~/sneat/assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="~/sneat/assets/js/config.js"></script>

</head>

<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->

            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
                <div class="app-brand demo">
                    <a asp-controller="Home" asp-action="Index" class="app-brand-link">
                        <span class="app-brand-logo demo">

                        </span>
                        <span class="app-brand-text demo menu-text fw-bolder ms-2">Kusys-Demo.Web</span>
                    </a>

                    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                        <i class="bx bx-chevron-left bx-sm align-middle"></i>
                    </a>
                </div>

                <div class="menu-inner-shadow"></div>

                <ul class="menu-inner py-1">
                    <!-- Student -->
                    <li class="menu-item">
                        <a asp-controller="Student" asp-action="Index" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-dock-top"></i>
                            <div data-i18n="Analytics">Student</div>
                        </a>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="menu-item">
                            <a asp-controller="Course" asp-action="Index" class="menu-link">
                                <i class="menu-icon tf-icons bx bx-collection"></i>
                                <div data-i18n="Analytics">Course</div>
                            </a>
                        </li>
                        <li class="menu-item">
                            <a asp-controller="Matching" asp-action="Index" class="menu-link">
                                <i class="menu-icon tf-icons bx bx-collection"></i>
                                <div data-i18n="Analytics">Matching</div>
                            </a>
                        </li>
                    }
                </ul>
            </aside>
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                     id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <!-- Search -->
                        <div class="navbar-nav align-items-center">
                            <div class="nav-item d-flex align-items-center">
                                <i class="bx bx-search fs-4 lh-0"></i>
                                <input type="text"
                                       class="form-control border-0 shadow-none"
                                       placeholder="Search..."
                                       aria-label="Search..." />
                            </div>
                        </div>
                        <!-- /Search -->

                        <ul class="navbar-nav flex-row align-items-center ms-auto">

                            <!-- User -->
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                    <div class="avatar avatar-online">
                                        <img src="~/sneat/assets/img/avatars/1.png" class="w-px-40 h-auto rounded-circle" />
                                    </div>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li>
                                        <a class="dropdown-item" href="#">
                                            <div class="d-flex">
                                                <div class="flex-shrink-0 me-3">
                                                    <div class="avatar avatar-online">
                                                        <img src="~/sneat/assets/img/avatars/1.png" class="w-px-40 h-auto rounded-circle" />
                                                    </div>
                                                </div>
                                                <div class="flex-grow-1">
                                                    <span class="fw-semibold d-block">@User.Identity.Name</span>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="dropdown-divider"></div>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="#">
                                            <i class="bx bx-user me-2"></i>
                                            <span class="align-middle">My Profile</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="#">
                                            <i class="bx bx-cog me-2"></i>
                                            <span class="align-middle">Settings</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="#">
                                            <span class="d-flex align-items-center align-middle">
                                                <i class="flex-shrink-0 bx bx-credit-card me-2"></i>
                                                <span class="flex-grow-1 align-middle">Billing</span>
                                                <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">4</span>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="dropdown-divider"></div>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Account" asp-action="Logout">
                                            <i class="bx bx-power-off me-2"></i>
                                            <span class="align-middle">Log Out</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <!--/ User -->
                        </ul>
                    </div>
                </nav>

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->

                    <div class="container-xxl flex-grow-1 container-p-y">
                        @RenderBody()
                    </div>
                    <!-- / Content -->
                    <!-- Footer -->
                    <footer class="content-footer footer bg-footer-theme">
                        <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                            <div class="mb-2 mb-md-0">
                                ©
                                <script>document.write(new Date().getFullYear());</script>
                                , made with ❤️ by
                                <a asp-controller="Home" asp-action="Index" class="footer-link fw-bolder">Home</a>
                            </div>
                            
                        </div>
                    </footer>
                    <!-- / Footer -->

                    <div class="content-backdrop fade"></div>
                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/sneat/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/sneat/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/sneat/assets/vendor/js/bootstrap.js"></script>
    <script src="~/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/DataTables/datatables.min.js"></script>
    <script src="~/sneat/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/sneat/assets/js/main.js"></script>

    <!-- Page JS -->
    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    @await RenderSectionAsync("Scripts", false);
</body>
</html>